### ISSUE TITLE
Cannot disable escaping of `&` in an attribute value

### ISSUE THREAD

**Issue by karollewandowski** [Kotlin/kotlinx.html#233]
I have a case where I pass an already escaped value to the attribute:
```
attributes["data-test"] = "Test: &hellip;"
```

I want it to be rendered as:
```
data-test="Test: &hellip;"
```

It is rendered as:
```
data-test="Test: &amp;hellip;"
```

I tried:
```
attributes["data-test"] = "Test: \\&hellip;"
```

but it becomes:
```
data-test="Test: \&amp;hellip;"
```

The context is the `a` tag.

**Comment by e5l** [comment]
Hey @karollewandowski, thanks for the PR. I will take a look

**Comment by e5l** [comment]
Fixed.
`0.11.0` available in the maven central

**Comment by prudencioj** [comment]
@e5l I believe this is still an issue in 0.11.0 version. 

Example:
a(href = "http://github.com/user=1&team=2")

The output will be "http://github.com/user=1&amp;team=2" which is not what we are expecting. The correct url should have "&" and not "&amp;".

**Comment by e5l** [comment]
Hey @prudencioj, it looks like the separate one for the parameter. Could you log it?
