### ISSUE TITLE
iOSARM64 artifact for 0.9.1 missing from Maven Central

### ISSUE THREAD

**Issue by Andy-TAG24** [Kotlin/kotlinx.html#234]
Hello, the central maven repo does not contain all artifcat files for `org.jetbrains.kotlinx:kotlinx-html-iosarm64:0.9.1`. I receive the following error:

```
Execution failed for task ':commonMain:kspKotlinIosArm64'.
> Could not resolve all files for configuration ':commonMain:iosArm64CompileKlibraries'.
   > Could not find org.jetbrains.kotlinx:kotlinx-html-iosarm64:0.9.1.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/org/jetbrains/kotlinx/kotlinx-html-iosarm64/0.9.1/kotlinx-html-iosarm64-0.9.1.pom
       - https://repo.maven.apache.org/maven2/org/jetbrains/kotlinx/kotlinx-html-iosarm64/0.9.1/kotlinx-html-iosarm64-0.9.1.pom
     Required by:
         project :commonMain > org.jetbrains.kotlinx:kotlinx-html:0.9.1

```

It seems that there are some files missing in
`https://repo.maven.apache.org/maven2/org/jetbrains/kotlinx/kotlinx-html-iosarm64/0.9.1/` . Could you please upload them to the maven repo?

Thanks in advance.

**Comment by e5l** [comment]
Hey @Andy-TAG24, thanks for the report. Should be available soon

**Comment by e5l** [comment]
Fixed

**Comment by francescotescari** [comment]
I'm still getting the same error and files are still missing at:
https://repo.maven.apache.org/maven2/org/jetbrains/kotlinx/kotlinx-html-iosarm64/0.9.1/
See the difference with
https://repo.maven.apache.org/maven2/org/jetbrains/kotlinx/kotlinx-html-iosarm64/0.9.0/

**Comment by e5l** [comment]
@francescotescari, thanks. It is the synchronization issue between the internal repo and maven central. Sorry, we're working on the fix

**Comment by e5l** [comment]
Hey, fixed with `0.10.1` release
